image: quay.io/fenicsproject/stable
 
pipelines:
  default:
    - step:
        script:
          - export HOME=/home/fenics
          - export FENICS_PREFIX=$HOME/local
          - export FENICS_PYTHON_MAJOR_VERSION=3
          - export FENICS_PYTHON_MINOR_VERSION=5
          - source $HOME/fenics.env.conf
          - cd $BITBUCKET_CLONE_DIR/src/MPET
          - pip3 install --no-cache-dir --upgrade --prefix=$FENICS_PREFIX .
          - python3 -m pytest -v test -m "not notpipelines"
          
